const images = {
welcome: {
    welcome1: require('../../assets/spring/welcome/welcome.jpg'),
    welcome2: require('../../assets/spring/welcome/welcome2.jpg'),
    welcome3: require('../../assets/spring/welcome/welcome3.jpg'),
    welcome4: require('../../assets/spring/welcome/welcome4.jpg'),
},
ad: [
   require('../../assets/spring/ad/ad1.jpg'),
   require('../../assets/spring/ad/ad2.jpg'),
   require('../../assets/spring/ad/adj1.jpg'),
   require('../../assets/spring/ad/ad4.jpg'),
   require('../../assets/spring/ad/ad5.jpg'),
   require('../../assets/spring/ad/ad6.jpg'),
   require('../../assets/spring/ad/ad7.jpg'),
   require('../../assets/spring/ad/ad8.jpg'),
   require('../../assets/spring/ad/ad9.jpg'),
   require('../../assets/spring/ad/ad10.jpg'),
   require('../../assets/spring/ad/ad11.jpg'),
   require('../../assets/spring/ad/ad12.jpg'),
   require('../../assets/spring/ad/ad13.jpg'),
   require('../../assets/spring/ad/ad14.jpg'),
   require('../../assets/spring/ad/ad16.jpg'),
   require('../../assets/spring/ad/ad17.jpg'),
   require('../../assets/spring/ad/ad19.jpg'),
   require('../../assets/spring/ad/ad20.jpg'),
   require('../../assets/spring/ad/ad21.jpg'),
   require('../../assets/spring/ad/ad22.jpg'),
   require('../../assets/spring/ad/ad24.jpg'),
],
big: [
    require('../../assets/spring/big/big1.jpg'),
    require('../../assets/spring/big/big2.jpg'),
     require('../../assets/spring/big/big3.jpg'),
     require('../../assets/spring/big/big4.jpg'),
     require('../../assets/spring/big/big5.jpg'),
     require('../../assets/spring/big/big6.jpg'),
     require('../../assets/spring/big/big7.jpg'),
     require('../../assets/spring/big/big8.jpg'),
     require('../../assets/spring/big/big9.jpg'),
     require('../../assets/spring/big/big10.jpg'),
],
ntl: [
   require('../../assets/spring/ntl/1.jpg'),
   require('../../assets/spring/ntl/2.jpg'),
   require('../../assets/spring/ntl/3.jpg'),
   require('../../assets/spring/ntl/4.jpg'),
   require('../../assets/spring/ntl/5.jpg'),
   require('../../assets/spring/ntl/6.jpg'),
   require('../../assets/spring/ntl/7.jpg'),
   require('../../assets/spring/ntl/8.jpg'),
   require('../../assets/spring/ntl/9.jpg'),
   require('../../assets/spring/ntl/10.jpg'),
   require('../../assets/spring/ntl/11.jpg'),
   require('../../assets/spring/ntl/12.jpg'),
   require('../../assets/spring/ntl/13.jpg'),
   require('../../assets/spring/ntl/14.jpg'),
   require('../../assets/spring/ntl/16.jpg'),
   require('../../assets/spring/ntl/17.jpg'),
   require('../../assets/spring/ntl/19.jpg'),
   require('../../assets/spring/ntl/20.jpg'),
   require('../../assets/spring/ntl/21.jpg'),
   require('../../assets/spring/ntl/22.jpg'),
   require('../../assets/spring/ntl/23.jpg'),
   require('../../assets/spring/ntl/24.jpg'),
   require('../../assets/spring/ntl/25.jpg'),
   require('../../assets/spring/ntl/26.jpg'),
   require('../../assets/spring/ntl/27.jpg'),
   require('../../assets/spring/ntl/28.jpg'),
   require('../../assets/spring/ntl/29.jpg'),
   require('../../assets/spring/ntl/30.jpg'),
   require('../../assets/spring/ntl/31.jpg'),
   require('../../assets/spring/ntl/32.jpg'),
   require('../../assets/spring/ntl/33.jpg'),
   require('../../assets/spring/ntl/34.jpg'),
   require('../../assets/spring/ntl/35.jpg'),
   require('../../assets/spring/ntl/36.jpg'),
   require('../../assets/spring/ntl/37.jpg'),
   require('../../assets/spring/ntl/38.jpg'),
   require('../../assets/spring/ntl/39.jpg'),
   require('../../assets/spring/ntl/40.jpg'),
   require('../../assets/spring/ntl/41.jpg'),
   require('../../assets/spring/ntl/42.jpg'),
   require('../../assets/spring/ntl/43.jpg'),
   require('../../assets/spring/ntl/44.jpg'),
   require('../../assets/spring/ntl/45.jpg'),
   require('../../assets/spring/ntl/46.jpg'),
   require('../../assets/spring/ntl/47.jpg'),
   require('../../assets/spring/ntl/48.jpg')
],
};

export default images;
